# Generated by Django 4.2.9 on 2025-05-25 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_publisher'),
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProfileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='카드 제목', max_length=100)),
                ('reading_style', models.CharField(blank=True, help_text='독서 스타일', max_length=100)),
                ('reading_time', models.CharField(blank=True, help_text='주로 읽는 시간대', max_length=50)),
                ('reading_place', models.CharField(blank=True, help_text='주로 읽는 장소', max_length=100)),
                ('mood', models.CharField(blank=True, help_text='나의 독서 무드 (예: 잔잔한, 몽환적인)', max_length=100)),
                ('introduction', models.TextField(blank=True, help_text='내 독서 취향에 대한 한 줄 소개')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_genres', models.ManyToManyField(help_text='좋아하는 장르 선택', related_name='preferred_by_profiles', to='books.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
