# Generated by Django 4.2.9 on 2025-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bookprofilecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprofilecard',
            name='favorite_genres',
        ),
        migrations.AlterField(
            model_name='bookprofilecard',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookprofilecard',
            name='mood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookprofilecard',
            name='reading_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookprofilecard',
            name='reading_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookprofilecard',
            name='reading_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bookprofilecard',
            name='favorite_genres',
            field=models.JSONField(default=list),
        ),
    ]
